services:

  zabbix-db:
    image: mysql:${MYSQL_VERSION}
    container_name: ${DB_CONTAINER_NAME}
    env_file: .env                                  # .env を読み込む

    environment:
      MYSQL_DATABASE:       ${MYSQL_DATABASE}
      MYSQL_USER:           ${MYSQL_USER}
      MYSQL_PASSWORD:       ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD:  ${MYSQL_ROOT_PASSWORD}

    command:
      - --max_allowed_packet=64M
      - --explicit_defaults_for_timestamp=1
      - --log-bin-trust-function-creators=1

    volumes:
      - ./zabbix-db:/var/lib/mysql

    restart: unless-stopped

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u$$MYSQL_USER", "-p$$MYSQL_PASSWORD"]
      interval: 5s
      timeout: 5s
      retries: 10


  zabbix-server:
    image: zabbix/zabbix-server-mysql:${ZABBIX_VERSION}
    container_name: ${ZABBIX_CONTAINER_NAME}
    env_file: .env                                  # .env を読み込む

    environment:
      DB_SERVER_HOST:   ${DB_SERVER_HOST}
      DB_SERVER_PORT:   ${DB_SERVER_PORT}
      MYSQL_DATABASE:   ${MYSQL_DATABASE}
      MYSQL_USER:       ${MYSQL_USER}
      MYSQL_PASSWORD:   ${MYSQL_PASSWORD}

    ports:
      - "${ZBX_TRAPPER_PORT}:10051"

    depends_on:
      zabbix-db:
        condition: service_healthy

    volumes:
      - ./zabbix_server.conf:/etc/zabbix/zabbix_server.conf

    restart: unless-stopped


  zabbix-web:
    image: zabbix/zabbix-web-nginx-mysql:${ZABBIX_VERSION}
    container_name: ${WEB_CONTAINER_NAME}
    env_file: .env                                  # .env を読み込む

    environment:
      DB_SERVER_HOST:   ${DB_SERVER_HOST}
      MYSQL_USER:       ${MYSQL_USER}
      MYSQL_PASSWORD:   ${MYSQL_PASSWORD}
      MYSQL_DATABASE:   ${MYSQL_DATABASE}
      ZBX_SERVER_HOST:  ${ZBX_SERVER_HOST}
      PHP_TZ:           ${PHP_TZ}

    ports:
      - "${WEB_PORT}:8080"

    depends_on:
      zabbix-server:
        condition: service_started
      zabbix-db:
        condition: service_healthy

    restart: unless-stopped
